---
init:
  # Build Vim
  - cd C:\
  - git clone https://github.com/vim/vim
  - cd vim
  - git checkout v8.0.0027
  - cd src
  - 'nmake -f Make_mvc2.mak CPU=AMD64 OLE=no GUI=no IME=yes MBYTE=yes
    ICONV=yes DEBUG=no FEATURES=NORMAL'

test_script:
  - echo hello world
