---
clone_depth: 10

init:
  # Stop git from changing newlines
  - git config --global core.autocrlf input

install:
  # Download and unpack Vim
  - cd C:\
  - ps: 'Invoke-WebRequest ftp://ftp.vim.org/pub/vim/pc/vim80-586w32.zip
    -OutFile C:\vim.zip'
  - ps: Add-Type -A System.IO.Compression.FileSystem
  - ps: "[IO.Compression.ZipFile]::ExtractToDirectory('vim.zip', 'vim')"

test_script:
  - C:\vim\vim80\vim.exe --version
  - echo hello world
