---
# Disabling building for AppVeyor. We are just testing things.
build: false
clone_depth: 10

init:
  # Stop git from changing newlines
  - git config --global core.autocrlf input

install:
  # Download and unpack Vim
  - cd C:\
  - ps: 'Invoke-WebRequest ftp://ftp.vim.org/pub/vim/pc/vim80-586w32.zip
    -OutFile C:\vim.zip'
  - ps: Add-Type -A System.IO.Compression.FileSystem
  - ps: "[IO.Compression.ZipFile]::ExtractToDirectory('C:\\vim.zip', 'C:\\vim')"
  # Set up Vader for tests
  - git clone https://github.com/junegunn/vader.vim C:\vader
  - cd C:\vader
  - git checkout -qf c6243dd81c98350df4dec608fa972df98fa2a3af
  - cd C:\

test_script:
  - C:\vim\vim\vim80\vim.exe --version
